### ISSUE TITLE
Cambio protocollo

### ISSUE THREAD

**Issue by flauteps** [FatturaElettronica/FatturaElettronica.IndicePA#1]
La versione 0.1 punta ancora su HTTP invece dovrebbe utilizzare HTTPS
Classe WebService
Campo RootUrl

**Comment by nicolaiarocci** [comment]
Ho rilasciato il progetto con il nuovo nome FatturaElettronica.IndicePA, più appropiato. Ora punta al HTTPS ed è NetStandard.
